altair>=4.1.0
networkx>=2.6.3
pandas<1.5.0  # 1.5.0 causes ValueError: columns cannot be a set when plotting altair facets